name: Install and Test

on:
  push:
  pull_request:
    branches:
      - develop
      - production

jobs:
  test-client-app:
    runs-on: ubuntu-latest
    env:
      working-directory: ./client-course-schedulizer
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: update-pnpm-version
        run: |
          pnpm install -g pnpm@latest
      - name: Install pnpm dependencies
        run: |
          pnpm install
        working-directory: ${{env.working-directory}}
      - name: Run tests
        run: |
          pnpm test
        working-directory: ${{env.working-directory}}
